[build-system]
    build-backend = "setuptools.build_meta"
    requires      = ["setuptools"]

[project]
    authors = [
        { name = "Diederik van der Boor", email = "opensource@edoburu.nl" },
        { name = "Timo Brembeck", email = "opensource@timo.brembeck.email" },
    ]
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Web Environment",
        "Framework :: Django :: 3.2",
        "Framework :: Django :: 4.1",
        "Framework :: Django :: 4.2",
        "Framework :: Django",
        "Framework :: Sphinx :: Extension",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
        "Topic :: Internet :: WWW/HTTP",
        "Topic :: Software Development :: Libraries :: Application Frameworks",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ]
    dependencies = ["Django>=3.2", "Sphinx>=3.4.0", "pprintpp"]
    description = "Improve the Sphinx autodoc for Django classes."
    dynamic = ["version"]
    keywords = ["django", "docstrings", "extension", "sphinx"]
    license = { text = "Apache2 2.0 License" }
    maintainers = [
        { name = "Timo Brembeck", email = "opensource@timo.brembeck.email" },
    ]
    name = "sphinxcontrib-django"
    readme = "README.rst"
    requires-python = ">=3.8"

    [project.urls]
        "Bug Tracker"   = "https://github.com/sphinx-doc/sphinxcontrib-django/issues"
        "Documentation" = "https://sphinxcontrib-django.readthedocs.io/"
        "Release Notes" = "https://github.com/sphinx-doc/sphinxcontrib-django/blob/main/CHANGES.rst"
        "Source Code"   = "https://github.com/sphinx-doc/sphinxcontrib-django"

    [project.optional-dependencies]
        dev = ["pre-commit"]
        doc = ["sphinx-last-updated-by-git", "sphinx-rtd-theme"]
        optional = [
            "django-mptt",
            "django-phonenumber-field[phonenumbers]",
            "psycopg2-binary",
        ]
        test = ["coverage", "pytest", "pytest-icdiff", "requests-mock"]

[tool.setuptools.dynamic]
    version = { attr = "sphinxcontrib_django.__version__" }

[tool.setuptools.packages.find]
    include = ["sphinxcontrib_django*"]

[tool.black]
    skip-magic-trailing-comma = true
    preview = true

[tool.coverage.run]
    command_line = "-m pytest"
    source       = ["sphinxcontrib_django"]

[tool.coverage.report]
    exclude_lines = [
        "pragma: no cover",
        "if TYPE_CHECKING:",
    ]

[tool.pytest.ini_options]
    addopts    = "-ra -vv --color=yes"
    minversion = "6.0"
    testpaths  = ["tests"]

[tool.ruff]
  select = [
    "F",
    "E",
    "W",
    "I",
    # "D",
    "RET",
    "SIM",
    "ANN",
  ]
  ignore = [
    "D1",   # Missing docstrings
    "ANN101",  # Annotation for 'self'
  ]
  line-length = 99

[tool.ruff.per-file-ignores]
  "tests/**/*.py" = ["ANN"] # TODO: tests are missing type annotations
